services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: leetlog-backend-prod
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: leetlog-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped